#!/bin/bash
# Quick Start Script for Rover with LiDAR Navigation

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🤖 FRR ROVER - QUICK START GUIDE 🤖                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Working Directory: $(pwd)"
echo ""

# Check if we're in the right directory
if [ ! -d "src/frr_bringup" ]; then
    echo "❌ Error: Not in frr_ws directory!"
    echo "Run: cd /home/alibaba/frr_ws"
    exit 1
fi

echo "✅ You're in the correct workspace"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 1: Source the Workspace"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Run this command:"
echo "  source install/setup.bash"
echo ""
read -p "Press Enter after you've sourced the workspace..."
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "STEP 2: Launch Rover (in THIS terminal)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Choose your configuration:"
echo ""
echo "1️⃣  Full System (LiDAR + Video + Obstacle Avoidance)"
echo "   ros2 launch frr_bringup rover_bringup.launch.py"
echo ""
echo "2️⃣  No Video (Save CPU)"
echo "   ros2 launch frr_bringup rover_bringup.launch.py enable_video_stream:=false"
echo ""
echo "3️⃣  No LiDAR (Direct control, no obstacle avoidance)"
echo "   ros2 launch frr_bringup rover_bringup.launch.py enable_lidar:=false"
echo ""
echo "4️⃣  Minimal (No video, no LiDAR)"
echo "   ros2 launch frr_bringup rover_bringup.launch.py enable_video_stream:=false enable_lidar:=false"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "STEP 3: Launch Teleop (in ANOTHER terminal)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "🔴 IMPORTANT: Open a NEW terminal and run:"
echo ""
echo "cd /home/alibaba/frr_ws"
echo "source install/setup.bash"
echo ""
echo "Then choose teleop mode:"
echo ""
echo "🛡️  With Obstacle Avoidance (if LiDAR enabled):"
echo "   ros2 run frr_control teleop_node --ros-args -r /cmd_vel:=/cmd_vel_teleop"
echo ""
echo "⚡ Direct Control (no obstacle avoidance):"
echo "   ros2 run frr_control teleop_node"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📊 MONITORING COMMANDS (optional, in 3rd terminal)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Check position (should start at 0,0):"
echo "ros2 topic echo /lidar_odom"
echo ""
echo "# Check for obstacles:"
echo "ros2 topic echo /obstacle_detected"
echo ""
echo "# View all topics:"
echo "ros2 topic list"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "⚙️  TUNING (while system is running)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Make obstacle avoidance more conservative:"
echo "ros2 param set /obstacle_avoidance_node safety_margin 0.20"
echo ""
echo "# Make obstacle avoidance more aggressive:"
echo "ros2 param set /obstacle_avoidance_node safety_margin 0.10"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "📖 DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "📄 INTEGRATED_BRINGUP_GUIDE.md  - Complete usage guide"
echo "📄 FINAL_INTEGRATION_STATUS.md  - System overview"
echo "📄 QUICK_START_LIDAR.md         - Quick reference"
echo "📄 DEPLOYMENT_CHECKLIST.md      - Testing procedures"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "Ready to launch! 🚀"
echo "═══════════════════════════════════════════════════════════"
